services:
  db:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - springboot-db-network

  ms:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - '8888:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user
    restart: on-failure
    networks:
      - springboot-db-network

networks:
  springboot-db-network:
    driver: bridge

volumes:
  db-data:
