apiVersion: v1
kind: Namespace
metadata:
  name: sj-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sj-ns
  name: sj-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sj-user
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sj-user
    spec:
      containers:
        - name: sj-user
          image: ${IMAGE_NAME}
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          env:
            - name: spring.datasource.url
              value: ${DATASOURCE_URL}

            - name: spring.datasource.username
              value: ${DATASOURCE_USER_ID}

            - name: spring.datasource.password
              value: ${DATASOURCE_SECRET}

            - name: spring.flyway.url
              value: ${DATASOURCE_URL}

            - name: spring.flyway.schemas
              value: ${DATASOURCE_USER_ID}

            - name: spring.flyway.user
              value: ${DATASOURCE_USER_ID}

            - name: spring.flyway.password
              value: ${DATASOURCE_SECRET}

            - name: aws.sns.topic.arn.job-seeker-status-update
              value: ${SNS_TOPIC_ARN}

            - name: pii.encrypt.key
              value: ${PII_ENCRYPT_KEY}

          imagePullPolicy: Always
          ports:
            - containerPort: 8080


