apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sj-user-autoscaling
  namespace: sj-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sj-user
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 10
          type: Pod
          value: 1
